import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from './components/Header'
import Menu from './components/Menu'
import React, { useState, useEffect } from 'react'
import Cursor from './components/Cursor'
import Loader from './components/Loader'
import Title from './components/Title'
import About_Main from './components/About_Main'
import Services from './components/Services'
import Skills from './components/Skills'
import Footer from './components/Footer'
import Color_Plate from './components/Color_Plate'
import ColrosLoader from './components/ColrosLoader'

export default function About() {
    const [menuOpen, setMenuOpen] = useState(false)
    const [themeColor, setThemeColor] = useState('')
    useEffect(() => {
        setThemeColor(JSON.parse(localStorage.getItem("colors")))
    }, [])

    const openMenu = () => {
        if (menuOpen) { setMenuOpen(false) } else { setMenuOpen(true) }
    }

    const colorChanger = (color) => {
        localStorage.setItem("colors", JSON.stringify(color))
        var ncolor = JSON.parse(localStorage.getItem("colors"))
        setThemeColor(ncolor)
    }

    return (
        <div className={styles.container} style={{ background: "#101010" }}>
            <Head>
                <title>PortFollio-About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Loader themeColor={themeColor} />
            <Cursor />
            <Menu menuOpen={menuOpen} openMenu={openMenu} />
            <Color_Plate colorChanger={colorChanger} />
            <Header openMenu={openMenu} menuOpen={menuOpen} />
            <Title title={"About"} sub_title={"Me"} desc={"Get to Know"} sub_desc={"me."} themeColor={themeColor} />
            <About_Main themeColor={themeColor} />
            <Title sup_title={"My "} title={"Services"} themeColor={themeColor} />
            <Services themeColor={themeColor} />
            <Title title={"My"} sub_title={"Skills"} themeColor={themeColor} />
            <Skills themeColor={themeColor} />
            <Footer themeColor={themeColor} />
        </div>
    )
}