import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from './components/Header'
import Main from './components/Main'
import Menu from './components/Menu'
import React, { useState } from 'react'
import Cursor from './components/Cursor'
import Loader from './components/Loader'
import ColrosLoader from './components/ColrosLoader'

export default function Home() {
    let color = ColrosLoader();
    const [menuOpen, setMenuOpen] = useState(false)
    
    const openMenu = () => {
        if (menuOpen) {
            setMenuOpen(false)
        }
        else {
            setMenuOpen(true)
        }
    }
    return (
        <div className={styles.container}>
            <Head>
                <title>PortFollio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <Loader themeColor={color}/>
            <Cursor/>
            <Menu menuOpen={menuOpen} openMenu={openMenu}/>
            <Header openMenu={openMenu} menuOpen={menuOpen} />
            <Main color={color} />
        </div>
    )
}
